services:
- type: web
  name: linebot_for_demo
  env: python
  repo: https://github.com/cherrytora/linebot
  buildCommand: pip install --upgrade pip && pip install -r requirements.txt && pip install uvicorn
  startCommand: python bot.py
  plan: free
  autoDeploy: true
  envVars:
  - key: PYTHON_VERSION 
    value: 3.11.5
  - key: LINE_CHANNEL_ACCESS_TOKEN
    sync: false
  - key: LINE_CHANNEL_SECRET
    sync: false
  network:
  - port: 8000
    protocol: https
    host: 0.0.0.0